### ISSUE TITLE
Adding definition of MOC regions southern transects to setup_MOC_basins

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/geometric_features#69]
The MOC and MHT AM's need both the MOC regions and their southern border for doing their computation. Since these two features need to be consistent with each other, I thought that the driver setup_MOC_basins could do both things:
1) define the MOC ocean basins;
2) pick the southern border of each so defined basin and make a new transect feature.
Does this sound like a reasonable thing to do?

**Comment by pwolfram** [comment]
@milenaveneziani, how were you planning on defining the southern border?  Were you going to specify at latitude such that the part of the polygon south of the latitude is the transect?

**Comment by milenaveneziani** [comment]
@pwolfram: each MOC region is defined by a specific southern latitude. I am thinking this is all that is needed as far as geojson files go. Then the mask creator will do its job, and I don't know whether it takes the southern/northern/or closest part of the polygon wrt that latitude.

**Comment by xylar** [comment]
@milenaveneziani and @pwolfram, I think 2) above would require a new tool and some new features in the repo.  The new tool would be `./intersect_features.py`, which would be the conceptual opposite of the `./difference_features.py` script: The source features would be masked to their intersection with the masking features(s) provided.  The new features would be transects running from -180 to 180 degrees at the southern boundary of each MOC region (similar to the MOC mask features but transects instead of regions).  Then, the desired southern boundary could be created as the intersections of these regions with the appropriate basin.

I will be happy to write this tool when I get back from France on the 17th.

**Comment by xylar** [comment]
@milenaveneziani wrote:
> Then the mask creator will do its job, and I don't know whether it takes the southern/northern/or closest part of the polygon wrt that latitude.

For each segment of each LineString in a transect feature, the mask creator will find a set of cell centers (and I believe also the edges and vertices, but I've not used that functionality) that are closest to that segment.  I assume you are after the transport across the southern boundary of each basin?  @mark-petersen has used transects in MPAS-O to compute transport so he may have some pointers.

Have you thought about the northern boundaries at all?  They are not as clean but could theoretically also be defined by transects.  Are they safe to ignore for some reason, whereas the southern boundaries definitely matter?

**Comment by mark-petersen** [comment]
@xylar, the MOC is computed as a stream function Psi(y,z) and can be computed from:
(1) dPsi/dz = V   (V is zonally averaged meridional velocity)
(2) dPsi/dy = W  (W is zonally averaged vertical velocity)
We typically integrate from south to north by latitude bins. For a global MOC Psi=0 at the southern boundary.  For a regional MOC, we integrate (1) downward in z along a transect (~35S for AMOC) and then integrate (2) northward.  That is why we need a matching transect and region for each regional MOC.  

We previously took the chance that the transect would not be exactly the boundary of the region, which could result in a small error in the MOC.

You could integrate (2) north to south.  The Atlantic has a cleaner boundary at 35S.

**Comment by xylar** [comment]
@mark-petersen, thanks for the very clear explanation.  I see now why only the southern boundaries are needed.

**Comment by xylar** [comment]
@mark-petersen and @milenaveneziani, I suspect the southern boundary transects as currently produced will not lead to the desired behavior when they are run through the mask creator  The issues are two:
  1.  The mask creator may not produce a series of edges that closely follow the southern-boundary transects.  I have found that the cell mask produced by the mask creator covers an arbitrary path between cell centers that are closest to points explicitly defined in the transect.  The result is a zig-zag that does not particularly closely approximate the original straight line. I suspect it will do the same between edges.  This issue can be mitigated by subdividing the transect so it has a large number of points (preferably more than one per grid cell so the closest cell center will always be found)
  2. Even if the mask creator were to find the edges that are closest to the transect defining the southern boundary, the transect (as defined by the mask creator) is the same as the collection of southern-most edges of the MOC region.  This is because cells are included in the MOC region when their cell center is within the region.  I don't think this guarantees that the correct edges (i.e. those with neighbors outside the MOC region) will belong to the collection of edges used to approximate the transect defining the southern boundary.

This is something we may need to test, but it also may not be possible to address this issue without modifying the mask creator.  That is, I'm rather sure the mask creator currently doesn't have the capability to ensure that a transect that is the border of a region corresponds to the edges that lie between the cells that are inside and those that are outside of the region.  This should be tested and an issue should be posted to MPAS-Tools to make this capability possible.

**Comment by mark-petersen** [comment]
When I implemented transects in matlab years ago, I would start with the edge closest to the starting point.  Then I would choose the next edge from the connecting edges (using edgesOnVertex and verticesOnEdge) that minimize the distance to the final point in (lat,lon) coordinates.  Those transects kept quite close to latitude lines, and did not zig-zag, probably because of my choice of minimizing (lat,lon) distance.  I put the matlab file here, if that is helpful:
https://gist.github.com/mark-petersen/117137a46ea3b126e30af69bd1d17c86

The main question is if this is 'close enough' to the region boundary, or if we really need to find the boundary edge for the transect.  If we are just a cell off here or there, I was going to live with it.  The error would be due to some horizontal divergence leading to vertical velocities in the 'missing' cells.

**Comment by xylar** [comment]
@mark-petersen, given that `geometric_features` defines features with lon/lat coordinates, I think it's appropriate to interpolate or find the closest cell in lon/lat space as opposed to using great circles or something like that.  Your code may be helpful for that.  If you or Nils see the zig-zagging I'm talking about, could you post an issue to `MPAS-Tools` and I'll try to fix the mask creator using your matlab script as a starting point.

I think the problem with using the closest edge is that there are sometimes cases where the transect crosses culled cells and you need to either break the transect into multiple subsets of edges with gaps between or follow a more indirect path that may not always bring you closer to the final point in order to find the final point.  Anyway, I think the mask creator needs some work...

**Comment by pwolfram** [comment]
@xylar and @mark-petersen, would https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm be helpful?  I'm guessing a transect between two points is most simply described as the shortest path along edges between the two points, right?  If so, this could also help deal with issues related to boundaries.

**Comment by xylar** [comment]
First, I'll say that I don't think this repo is the right place to be having this conversation and I would rather we start an issue under MPAS-Tools.

@pwolfram, that could work if we really want to have a complete path for each transect with no gaps at culled cells.  I would think a simpler algorithm like Mark's could work as long as we are willing to allow gaps in a transect where there is land.  It depends on our needs.

@mark-petersen, the transects in this repo that define the southern boundaries *do* have gaps at at the moment when they run into land features.  It would seem reasonable to me if there were also gaps for culled cells on the MPAS-O side but it depends on the specific needs.  Do you really need a single, continuous transect for each feature?  If so, I will need a more sophisticated algorithm for finding the southern boundary of each MOC region than I currently have.

**Comment by xylar** [comment]
I'm going to close this issue because I think we've moved this work to MPAS-Tools.
